In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df=pd.read_csv(r"D:\foodie-intelligence-system\data\order_history_kaggle_data.csv")

In [3]:
df.head(5)

,Restaurant ID,Restaurant name,Subzone,City,Order ID,Order Placed At,Order Status,Delivery,Distance,Items in order,...,Rating,Review,Cancellation / Rejection reason,Restaurant compensation (Cancellation),Restaurant penalty (Rejection),KPT duration (minutes),Rider wait time (minutes),Order Ready Marked,Customer complaint tag,Customer ID
0,20320607,Swaad,Sector 4,Delhi NCR,6168884918,"11:38 PM, September 10 2024",Delivered,Zomato Delivery,3km,"1 x Grilled Chicken Jamaican Tender, 1 x Grill...",...,NaN,NaN,NaN,NaN,NaN,18.35,11.6,Correctly,NaN,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...
1,20320607,Swaad,Sector 4,Delhi NCR,6170707559,"11:34 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Fries, 1 x Fried Chicken Angara ...",...,NaN,NaN,NaN,NaN,NaN,16.95,3.6,Correctly,NaN,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...
2,20320607,Swaad,Sector 4,Delhi NCR,6169375019,"03:52 PM, September 10 2024",Delivered,Zomato Delivery,<1km,1 x Bone in Peri Peri Grilled Chicken,...,NaN,NaN,NaN,NaN,NaN,14.05,12.2,Correctly,NaN,f93362f5ce5382657482d164e368186bcec9c6225fd93d...
3,20320607,Swaad,Sector 4,Delhi NCR,6151677434,"03:45 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Fried Chicken Ghostbuster Tender, 1 x Anga...",...,4.0,NaN,NaN,NaN,NaN,19.00,3.3,Correctly,NaN,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...
4,20320607,Swaad,Sector 4,Delhi NCR,6167540897,"03:04 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Krispers, 1 x Fried Chicken Anga...",...,NaN,NaN,NaN,NaN,NaN,15.97,1.0,Correctly,NaN,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...

In [4]:
df.columns

Index(['Restaurant ID', 'Restaurant name', 'Subzone', 'City', 'Order ID',
       'Order Placed At', 'Order Status', 'Delivery', 'Distance',
       'Items in order', 'Instructions', 'Discount construct', 'Bill subtotal',
       'Packaging charges', 'Restaurant discount (Promo)',
       'Restaurant discount (Flat offs, Freebies & others)', 'Gold discount',
       'Brand pack discount', 'Total', 'Rating', 'Review',
       'Cancellation / Rejection reason',
       'Restaurant compensation (Cancellation)',
       'Restaurant penalty (Rejection)', 'KPT duration (minutes)',
       'Rider wait time (minutes)', 'Order Ready Marked',
       'Customer complaint tag', 'Customer ID'],
      dtype='object')

In [5]:
df.rename(columns={'Restaurant ID':'Resto_ID','Restaurant name':'Resto_name','Order ID':'Order_ID','Order Placed At':'Order_Placed_At','Order Status':'Order_status','Items in order':'Items_in_order','Discount construct':'Discount_construct','Bill subtotal':'Bill_subtotal','Packaging charges':'Packaging_charges','Restaurant discount (Promo)':'Restaurant_discount_(Promo)','Restaurant discount (Flat offs, Freebies & others)':'Restaurant_discount_(Flat offs, Freebies & others)','Gold discount':'Gold_discount','Brand pack discount':'Brand_pack_discount','Cancellation / Rejection reason':'Cancellation/Rejection_reason','Restaurant compensation (Cancellation)':'Restaurant_compensation_(Cancellation)','Restaurant penalty (Rejection)':'Restaurant_penalty_(Rejection)','KPT duration (minutes)':'KPT_duration_(minutes)','Rider wait time (minutes)':'Rider_wait_time_(minutes)','Order Ready Marked':'Order_Ready_Marked','Customer complaint tag':'Customer_complaint_tag','Customer ID':'Customer_ID'}, inplace=True)
df.columns

Index(['Resto_ID', 'Resto_name', 'Subzone', 'City', 'Order_ID',
       'Order_Placed_At', 'Order_status', 'Delivery', 'Distance',
       'Items_in_order', 'Instructions', 'Discount_construct', 'Bill_subtotal',
       'Packaging_charges', 'Restaurant_discount_(Promo)',
       'Restaurant_discount_(Flat offs, Freebies & others)', 'Gold_discount',
       'Brand_pack_discount', 'Total', 'Rating', 'Review',
       'Cancellation/Rejection_reason',
       'Restaurant_compensation_(Cancellation)',
       'Restaurant_penalty_(Rejection)', 'KPT_duration_(minutes)',
       'Rider_wait_time_(minutes)', 'Order_Ready_Marked',
       'Customer_complaint_tag', 'Customer_ID'],
      dtype='object')

In [6]:
df.head()

,Resto_ID,Resto_name,Subzone,City,Order_ID,Order_Placed_At,Order_status,Delivery,Distance,Items_in_order,...,Rating,Review,Cancellation/Rejection_reason,Restaurant_compensation_(Cancellation),Restaurant_penalty_(Rejection),KPT_duration_(minutes),Rider_wait_time_(minutes),Order_Ready_Marked,Customer_complaint_tag,Customer_ID
0,20320607,Swaad,Sector 4,Delhi NCR,6168884918,"11:38 PM, September 10 2024",Delivered,Zomato Delivery,3km,"1 x Grilled Chicken Jamaican Tender, 1 x Grill...",...,NaN,NaN,NaN,NaN,NaN,18.35,11.6,Correctly,NaN,5d6c2b96db963098bc69768bea504c8bf46106a8a5178e...
1,20320607,Swaad,Sector 4,Delhi NCR,6170707559,"11:34 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Fries, 1 x Fried Chicken Angara ...",...,NaN,NaN,NaN,NaN,NaN,16.95,3.6,Correctly,NaN,0781815deb4a10a574e9fee4fa0b86b074d4a0b36175d5...
2,20320607,Swaad,Sector 4,Delhi NCR,6169375019,"03:52 PM, September 10 2024",Delivered,Zomato Delivery,<1km,1 x Bone in Peri Peri Grilled Chicken,...,NaN,NaN,NaN,NaN,NaN,14.05,12.2,Correctly,NaN,f93362f5ce5382657482d164e368186bcec9c6225fd93d...
3,20320607,Swaad,Sector 4,Delhi NCR,6151677434,"03:45 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Fried Chicken Ghostbuster Tender, 1 x Anga...",...,4.0,NaN,NaN,NaN,NaN,19.00,3.3,Correctly,NaN,1ed226d1b8a5f7acee12fc1d6676558330a3b2b742af5d...
4,20320607,Swaad,Sector 4,Delhi NCR,6167540897,"03:04 PM, September 10 2024",Delivered,Zomato Delivery,2km,"1 x Peri Peri Krispers, 1 x Fried Chicken Anga...",...,NaN,NaN,NaN,NaN,NaN,15.97,1.0,Correctly,NaN,d21a2ac6ea06b31cc3288ab20c4ef2f292066c096f2c5f...

In [7]:
df.isnull().sum()

Resto_ID                                                  0
Resto_name                                                0
Subzone                                                   0
City                                                      0
Order_ID                                                  0
Order_Placed_At                                           0
Order_status                                              0
Delivery                                                  0
Distance                                                  0
Items_in_order                                            0
Instructions                                          20601
Discount_construct                                     5498
Bill_subtotal                                             0
Packaging_charges                                         0
Restaurant_discount_(Promo)                               0
Restaurant_discount_(Flat offs, Freebies & others)        0
Gold_discount                                             0
Brand_pack_discount                                       0
Total                                                     0
Rating                                                18830
Review                                                21025
Cancellation/Rejection_reason                         21135
Restaurant_compensation_(Cancellation)                21188
Restaurant_penalty_(Rejection)                        21318
KPT_duration_(minutes)                                  295
Rider_wait_time_(minutes)                               168
Order_Ready_Marked                                        0
Customer_complaint_tag                                20852
Customer_ID                                               0
dtype: int64

In [8]:
df.dtypes

Resto_ID                                                int64
Resto_name                                             object
Subzone                                                object
City                                                   object
Order_ID                                                int64
Order_Placed_At                                        object
Order_status                                           object
Delivery                                               object
Distance                                               object
Items_in_order                                         object
Instructions                                           object
Discount_construct                                     object
Bill_subtotal                                         float64
Packaging_charges                                     float64
Restaurant_discount_(Promo)                           float64
Restaurant_discount_(Flat offs, Freebies & others)    float64
Gold_discount                                         float64
Brand_pack_discount                                   float64
Total                                                 float64
Rating                                                float64
Review                                                 object
Cancellation/Rejection_reason                          object
Restaurant_compensation_(Cancellation)                float64
Restaurant_penalty_(Rejection)                        float64
KPT_duration_(minutes)                                float64
Rider_wait_time_(minutes)                             float64
Order_Ready_Marked                                     object
Customer_complaint_tag                                 object
Customer_ID                                            object
dtype: object

In [9]:
df['Instructions']=df['Instructions'].fillna('No Instrutions')
df['Dicount_construct']=df['Discount_construct'].fillna('No Discount')
df['Rating']=df['Rating'].fillna('Not Rated')
df.drop('Cancellation/Rejection_reason',axis=1,inplace=True)
df.drop('Restaurant_compensation_(Cancellation)',axis=1,inplace=True)
df.drop('Restaurant_penalty_(Rejection)',axis=1,inplace=True)
df['KPT_duration_(minutes)']=df['KPT_duration_(minutes)'].fillna(df['KPT_duration_(minutes)'].median())
df['Rider_wait_time_(minutes)']=df['Rider_wait_time_(minutes)'].fillna(df['Rider_wait_time_(minutes)'].median())
df.drop('Customer_complaint_tag',axis=1,inplace=True)

In [10]:
df.isnull().sum()

Resto_ID                                                  0
Resto_name                                                0
Subzone                                                   0
City                                                      0
Order_ID                                                  0
Order_Placed_At                                           0
Order_status                                              0
Delivery                                                  0
Distance                                                  0
Items_in_order                                            0
Instructions                                              0
Discount_construct                                     5498
Bill_subtotal                                             0
Packaging_charges                                         0
Restaurant_discount_(Promo)                               0
Restaurant_discount_(Flat offs, Freebies & others)        0
Gold_discount                                             0
Brand_pack_discount                                       0
Total                                                     0
Rating                                                    0
Review                                                21025
KPT_duration_(minutes)                                    0
Rider_wait_time_(minutes)                                 0
Order_Ready_Marked                                        0
Customer_ID                                               0
Dicount_construct                                         0
dtype: int64

In [11]:
df['Discount_construct'] = df['Discount_construct'].replace(['', 'null', 'None'], None)

In [12]:
df['Discount_construct'] = df['Discount_construct'].fillna('No Discount')

In [13]:
df.isnull().sum()

Resto_ID                                                  0
Resto_name                                                0
Subzone                                                   0
City                                                      0
Order_ID                                                  0
Order_Placed_At                                           0
Order_status                                              0
Delivery                                                  0
Distance                                                  0
Items_in_order                                            0
Instructions                                              0
Discount_construct                                        0
Bill_subtotal                                             0
Packaging_charges                                         0
Restaurant_discount_(Promo)                               0
Restaurant_discount_(Flat offs, Freebies & others)        0
Gold_discount                                             0
Brand_pack_discount                                       0
Total                                                     0
Rating                                                    0
Review                                                21025
KPT_duration_(minutes)                                    0
Rider_wait_time_(minutes)                                 0
Order_Ready_Marked                                        0
Customer_ID                                               0
Dicount_construct                                         0
dtype: int64

In [14]:
df['Distance'] = df['Distance'].str.replace('km', '')
df['Distance'] = df['Distance'].str.strip()

In [15]:
df['Distance'] = pd.to_numeric(df['Distance'], errors='coerce')

In [16]:
df['Order_Placed_At']=pd.to_datetime(df['Order_Placed_At'])
numeric_cols = [
    'Distance',
    'Bill_subtotal',
    'Packaging_charges',
    'Restaurant_discount_(Promo)',
    'Restaurant_discount_(Flat offs, Freebies & others)',
    'Gold_discount',
    'Brand_pack_discount',
    'Total',
    'KPT_duration_(minutes)',
    'Rider_wait_time_(minutes)'
]
for col in numeric_cols:
    if col != 'Distance':
        df[col] = pd.to_numeric(df[col], errors='coerce')

C:\Users\HP\AppData\Local\Temp\ipykernel_11684\3332377265.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Order_Placed_At']=pd.to_datetime(df['Order_Placed_At'])

In [17]:
df.dtypes

Resto_ID                                                       int64
Resto_name                                                    object
Subzone                                                       object
City                                                          object
Order_ID                                                       int64
Order_Placed_At                                       datetime64[ns]
Order_status                                                  object
Delivery                                                      object
Distance                                                     float64
Items_in_order                                                object
Instructions                                                  object
Discount_construct                                            object
Bill_subtotal                                                float64
Packaging_charges                                            float64
Restaurant_discount_(Promo)                                  float64
Restaurant_discount_(Flat offs, Freebies & others)           float64
Gold_discount                                                float64
Brand_pack_discount                                          float64
Total                                                        float64
Rating                                                        object
Review                                                        object
KPT_duration_(minutes)                                       float64
Rider_wait_time_(minutes)                                    float64
Order_Ready_Marked                                            object
Customer_ID                                                   object
Dicount_construct                                             object
dtype: object

In [19]:
df['Order_Placed_At'] = pd.to_datetime(df['Order_Placed_At'], errors='coerce')
df['Order_Placed_At'].dtype

dtype('<M8[ns]')

In [20]:
df['order_date'] = df['Order_Placed_At'].dt.date
df['order_hour'] = df['Order_Placed_At'].dt.hour
df['order_day_name'] = df['Order_Placed_At'].dt.day_name()
df['order_month'] = df['Order_Placed_At'].dt.month
df['is_weekend'] = df['Order_Placed_At'].dt.dayofweek >= 5

In [21]:
df[['Order_Placed_At', 'order_date', 'order_hour', 'order_day_name', 'order_month', 'is_weekend']].head()

,Order_Placed_At,order_date,order_hour,order_day_name,order_month,is_weekend
0,2024-09-10 23:38:00,2024-09-10,23,Tuesday,9,False
1,2024-09-10 23:34:00,2024-09-10,23,Tuesday,9,False
2,2024-09-10 15:52:00,2024-09-10,15,Tuesday,9,False
3,2024-09-10 15:45:00,2024-09-10,15,Tuesday,9,False
4,2024-09-10 15:04:00,2024-09-10,15,Tuesday,9,False

In [23]:
df.dtypes

Resto_ID                                                       int64
Resto_name                                                    object
Subzone                                                       object
City                                                          object
Order_ID                                                       int64
Order_Placed_At                                       datetime64[ns]
Order_status                                                  object
Delivery                                                      object
Distance                                                     float64
Items_in_order                                                object
Instructions                                                  object
Discount_construct                                            object
Bill_subtotal                                                float64
Packaging_charges                                            float64
Restaurant_discount_(Promo)                                  float64
Restaurant_discount_(Flat offs, Freebies & others)           float64
Gold_discount                                                float64
Brand_pack_discount                                          float64
Total                                                        float64
Rating                                                        object
Review                                                        object
KPT_duration_(minutes)                                       float64
Rider_wait_time_(minutes)                                    float64
Order_Ready_Marked                                            object
Customer_ID                                                   object
Dicount_construct                                             object
order_date                                                    object
order_hour                                                     int32
order_day_name                                                object
order_month                                                    int32
is_weekend                                                      bool
dtype: object

In [25]:
df['total_discount']=(
    df['Restaurant_discount_(Promo)']+df['Restaurant_discount_(Flat offs, Freebies & others)']+df['Gold_discount']+df['Brand_pack_discount']
)

In [26]:
df[['Restaurant_discount_(Promo)',
    'Restaurant_discount_(Flat offs, Freebies & others)',
    'Gold_discount',
    'Brand_pack_discount',
    'total_discount']].head()

,Restaurant_discount_(Promo),"Restaurant_discount_(Flat offs, Freebies & others)",Gold_discount,Brand_pack_discount,total_discount
0,80.0,0.0,0.0,0.0,80.0
1,175.0,0.0,0.0,0.0,175.0
2,80.0,0.0,0.0,0.0,80.0
3,80.0,0.0,0.0,0.0,80.0
4,80.0,0.0,0.0,0.0,80.0

In [28]:
df['final_order_value'] = df['Total']
df[['Total', 'final_order_value']].head()

     Total  final_order_value
0   666.75             666.75
1  1054.20            1054.20
2   241.50             241.50
3   567.00             567.00
4   529.20             529.20

In [30]:
import os

os.makedirs('data/cleaned', exist_ok=True)

df.to_csv('data/cleaned/cleaned_food_orders.csv', index=False)